### ISSUE TITLE
To be improved: Configure the template accordingly using the chart name as root element

### ISSUE THREAD

**Issue by cmoulliard** [snowdrop/helm#3]
## To be improved

This section of the README is not clear as you dont explain in which file the information should be added

```
Configure the template accordingly using the chart name as root element:

spring-boot-example-app: # This is the chart name from the dependencies!
  name: rest-http
  version: 2.5.0-0-SNAPSHOT
  s2i:
    source:
      repo: https://github.com/snowdrop/rest-http-example
      ref: sb-2.5.x
```
